import type { Metadata } from "next";
import { Sora,Sono } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
const sora = Sora({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-sora",
});
const sono = Sono({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-sono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${sora.className} ${sono.variable} antialiased`}
      >
         <NextTopLoader color="#003DEF" height={4} showSpinner={false} />
        {children}
      </body>
    </html>
  );
}
