import type { Metadata } from "next";
import { Sora } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import Sidebar from "@/components/layout/Sidebar";
import MobileHeader from "@/components/layout/MobileHeader";
const sora = Sora({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-fredoka",
});

export const metadata: Metadata = {
  title: {
    template: "%s | Capita",
    default: "Welcome | Capita",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${sora.className}  overflow-x-hidde no-scrollbar  min-h-screen max-w-[144rem] mx-auto my-0 antialiased`}
      >
        <NextTopLoader color="#003DEF" height={4} showSpinner={false} />
        <div className="flex flex-col absolute  lg:grid lg:grid-cols-[11rem_1fr] w-full">
          <div className="hidden lg:block">
            <Sidebar />
          </div>

          <div className="block lg:hidden">
            <MobileHeader />
          </div>
          <div className="flex flex-col pt-16 lg:pt-0   no-scrollbar  overflow-x-hidden overflow-y-scroll relative h-screen  min-w-0 px-3 md:px-6 py-5">
            {children}
            <div className="py-5"/>
          </div>
        </div>
      </body>
    </html>
  );
}
